all:
	#make -C AirLinked/PWMBOX clean
	#make -C AirLinked/PWMBOX all
	#make -C AirLinked/RGBBOX clean
	#make -C AirLinked/RGBBOX all
	#make -C AirLinked/UVCBOX clean
	#make -C AirLinked/UVCBOX all
	make -C CCD clean
	make -C CCD all
	make -C CUL clean
	make -C CUL all
	make -C CUL-Arduino clean
	make -C CUL-Arduino all
	make -C CUL-ProMicro clean
	make -C CUL-ProMicro all
	make -C CUN clean
	make -C CUN all
	make -C CUNO clean 
	make -C CUNO all 
	make -C CUNO2 clean
	make -C CUNO2 all
	make -C CUR clean
	make -C CUR all
	make -C COC clean
	make -C COC all
	make -C CPM-BS clean
	make -C CPM-BS all
	make -C PIGATOR clean
	make -C PIGATOR all
	make -C CPM-Gardenabodenfeuchtesensor/Release clean
	make -C CPM-Gardenabodenfeuchtesensor/Release all 
	make -C miniCUL clean
	make -C miniCUL all
	make -C nanoCUL clean
	make -C nanoCUL all
	make -C SCC clean
	make -C SCC all
	make -C RFbee clean
	make -C RFbee all
	make -C TuxRadio clean
	make -C TuxRadio all
	make -C TuxRadio2 clean
	make -C TuxRadio2 all
	make -C CSM clean
	make -C CSM all
	make -C CSM_RADINO clean
	make -C CSM_RADINO all
	make -C CPM-BS clean
	make -C CPM-BS all
	make -C zCSM clean
	make -C zCSM all
	make -C rpiaddon clean
	make -C rpiaddon all
	make -C CUL-HM-CFG clean
	make -C CUL-HM-CFG all
	make -C CUL-HM-CFG/bootloader clean
	make -C CUL-HM-CFG/bootloader all
	make -C CUBe clean
	make -C CUBe all
	make -C CUBe/bootloader clean
	make -C CUBe/bootloader all
	make -C MapleCUN clean
	make -C MapleCUN all
	make -C I2CCUL clean
	make -C I2CCUL all
	find . -name \*.eep | xargs rm
	find . -name \*.elf | xargs rm
	find . -name \*.lss | xargs rm
	find . -name \*.lst | xargs rm
	find . -name \*.map | xargs rm
	find . -name \*.sym | xargs rm
	find . -name \*.o | xargs rm

clean:
	make -C AirLinked/PWMBOX clean
	make -C AirLinked/RGBBOX clean
	make -C AirLinked/UVCBOX clean
	make -C CCD clean
	make -C CUL clean
	make -C CUL-Arduino clean
	make -C CUL-ProMicro clean
	make -C CUN clean
	make -C CUNO clean 
	make -C CUNO2 clean
	make -C CUR clean
	make -C COC clean
	make -C CPM-BS clean
	make -C PIGATOR clean
	make -C CPM-Gardenabodenfeuchtesensor/Release clean
	make -C miniCUL clean
	make -C nanoCUL clean
	make -C SCC clean
	make -C TuxRadio clean
	make -C TuxRadio2 clean
	make -C CSM clean
	make -C CSM_RADINO clean
	make -C CPM-BS clean
	make -C RFbee clean
	make -C rpiaddon clean
	make -C zCSM clean
	make -C CUL-HM-CFG clean
	make -C CUL-HM-CFG/bootloader clean
	make -C CUBe clean
	make -C CUBe/bootloader clean
	make -C MapleCUN clean
	make -C I2CCUL clean
	
